### ISSUE TITLE
selenium

### ISSUE THREAD

**Issue by ShurikenTYY** [kgsensei/NitroType-AutoTyper#2]
i downloaded the py file and have the hacked driver in the same folder as the py file but you dont tell us what to do after that

**Comment by kgsensei** [comment]
Run the python file.

**Comment by ShurikenTYY** [comment]
what do you use to run python files

**Comment by kgsensei** [comment]
Python.

**Comment by javesc** [comment]
ok put a vidoe to show us how to do it

**Comment by Bhupi-CSE** [comment]
As others have suggested, you can open Pycharm community version IDE  and open either create new project where you can add that existing py file and make sure that all the imports are properly done (installed on your computer using pip command) after that it should be a breeze like right click on py file and run/debug and analyze if this is doing as intended, reach out to me in case you have additional queries/issues

**Comment by oslasher** [comment]
just give me a tutorial on it it's too complicated i still don't know what to do

**Comment by kgsensei** [comment]
If you want you can use the new version. It should be much easier to use.
